"use client";
import { useEffect } from "react";
import Lenis from "lenis";
import { motion, useReducedMotion, useScroll, useSpring } from "motion/react";
import { projects, stack } from "../data";

const experience=[
 {name:"Meatguy Ecosystem",role:"Full-Stack Web Developer",period:"Dec 2024 — Present",url:"https://meatguysteakhouse.com",tech:"Nuxt 3 · Express · PostgreSQL",scope:"Public website, internal CMS, CRM capabilities, campaigns, integrations, and operational tooling."},
 {name:"Grillz by Meatguy",role:"Full-Stack Web Developer",period:"PT Daging Grup Indonesia",url:"https://grillz.id",tech:"Nuxt 3 · GSAP · Nginx",scope:"Standalone brand website for private steak experiences, including scroll-led storytelling, enquiry paths, and production deployment."},
 {name:"Golden Sugar",role:"Full-Stack Web Developer",period:"2025 — Present",url:"https://goldensugar.id",tech:"Nuxt 3 · CMS · APIs",scope:"Customer-facing brand platform connected to an internal content and operational CMS."},
 {name:"Marbl",role:"Full-Stack Web Developer",period:"2025 — Present",url:"https://marbl.id",tech:"Modern Web Stack",scope:"Digital product delivery across interface, application logic, and production deployment."},
 {name:"Meatgainz",role:"Full-Stack Web Developer",period:"2025 — Present",url:"https://meatgainz.id",tech:"Modern Web Stack",scope:"Product website and supporting digital experience within the PT Daging Grup Indonesia ecosystem."},
 {name:"GSTC",role:"Full-Stack Developer · Freelance",period:"Pre–Dec 2024",url:"https://www.gstcouncil.org",tech:"Next.js",scope:"Content-heavy company profile work with multilingual delivery and close UI/UX collaboration."},
 {name:"Sirlo Steak",role:"Full-Stack Developer · Freelance",period:"Pre–Dec 2024",url:"https://sirlosteak.com",tech:"Next.js · NestJS",scope:"Website, content management system, and reservation workflow delivered end to end."}
];
const techLogos:Record<string,string>={"Next.js":"nextdotjs/ffffff","Nuxt 3":"nuxt/00DC82",React:"react/61DAFB",Vue:"vuedotjs/4FC08D",TypeScript:"typescript/3178C6","Node.js":"nodedotjs/5FA04E",NestJS:"nestjs/E0234E",Express:"express/ffffff",PostgreSQL:"postgresql/4169E1","Tailwind CSS":"tailwindcss/06B6D4","REST APIs":"fastapi/009688","AI Integrations":"openai/ffffff"};
const excludedWork=new Set(["Meatguy × Chope Reservations","Grillz Website","Hampers Campaign","Miyazaki Wagyu Campaign","Careers Platform"]);
const selected=projects.slice(4).filter(project=>!excludedWork.has(project.title));
const capture=(url:string)=>`https://image.thum.io/get/width/1800/crop/1120/noanimate/${url}`;
function Arrow(){return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 19 19 5M8 5h11v11"/></svg>}

export default function Portfolio(){
 const reduced=useReducedMotion();const{scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:100,damping:25});
 useEffect(()=>{if(reduced)return;const lenis=new Lenis({duration:1.05,smoothWheel:true});let frame=0;const raf=(t:number)=>{lenis.raf(t);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(frame);lenis.destroy()}},[reduced]);
 const reveal=reduced?{initial:false as const}:{initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-10%"},transition:{duration:.7,ease:[.16,1,.3,1] as [number,number,number,number]}};
 return <main id="top">
  <motion.div className="progress" style={{scaleX:progress}}/>
  <header className="site-head"><a className="wordmark" href="#top"><span>Hendi</span> Saputra</a><p>Full-stack developer<br/>Jakarta · Indonesia</p><nav aria-label="Primary navigation"><a href="#experience">Experience</a><a href="#work">Work</a><a href="#about">About</a></nav><a className="head-cta" href="#contact">Let&apos;s talk <Arrow/></a></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><i/> Available for the right team</p><motion.h1 initial={reduced?false:{opacity:0,y:36}} animate={{opacity:1,y:0}} transition={{duration:.9,ease:[.16,1,.3,1]}}>Building digital products from interface to intelligence.</motion.h1><div className="hero-bottom"><p>I&apos;m Hendi, a full-stack web developer building web platforms, internal systems, integrations, and AI-assisted workflows.</p><a href="#experience">Explore experience <span>↓</span></a></div></div><motion.figure className="portrait" initial={reduced?false:{clipPath:"inset(100% 0 0 0)"}} animate={{clipPath:"inset(0% 0 0 0)"}} transition={{duration:1.1,delay:.15,ease:[.16,1,.3,1]}}><img src="/hendi-portrait.webp" alt="Hendi Saputra, Full-Stack Web Developer"/><figcaption><span>01 / Portrait</span><span>PT Daging Grup Indonesia · 2024—Now</span></figcaption></motion.figure></section>
  <div className="tech-marquee" aria-label="Technology stack"><div>{[...stack,...stack].map((item,index)=><span key={`${item}-${index}`}><img src={`https://cdn.simpleicons.org/${techLogos[item]}`} alt=""/><b>{item}</b></span>)}</div></div>
  <section className="statement" id="about"><div className="section-label"><span>01</span><p>What I bring</p></div><motion.div className="statement-copy" {...reveal}><p>Not just pages. I work across the whole product loop—interface, API, data, infrastructure, integration, and iteration.</p><div className="service-list"><article><span>01</span><h3>Web platforms</h3><p>Fast public experiences and internal tools engineered around real business workflows.</p></article><article><span>02</span><h3>Full-stack systems</h3><p>Practical architecture from data models and APIs through deployment and observability.</p></article><article><span>03</span><h3>AI &amp; automation</h3><p>AI-assisted flows and integrations that reduce repetitive work instead of adding novelty.</p></article></div></motion.div></section>
  <section className="experience" id="experience"><div className="experience-head"><div className="section-label"><span>02</span><p>Experience</p></div><div><h2>Main products &amp; collaborations.</h2><p>High-level project ownership first. The specific systems shipped inside them are documented below.</p></div></div><div className="experience-list">{experience.map((item,index)=><motion.a className="experience-row" href={item.url} target="_blank" rel="noreferrer" key={item.name} {...reveal}><span className="experience-no">{String(index+1).padStart(2,"0")}</span><div className="experience-shot"><img src={capture(item.url)} alt={`${item.name} website`} loading="lazy"/></div><div className="experience-title"><h3>{item.name}</h3><p>{item.role}</p></div><div className="experience-scope"><p>{item.scope}</p><span>{item.tech}</span></div><div className="experience-period"><span>{item.period}</span><Arrow/></div></motion.a>)}</div></section>
  <section className="selected-work" id="work"><div className="selected-head"><div className="section-label"><span>03</span><p>Selected work</p></div><div><h2>Inside the build.</h2><p>Breakdowns of the features, integrations, and operational systems I helped ship.</p></div></div><div className="work-list">{selected.map((project,index)=><motion.article className="work-row" key={project.title} {...reveal}><div className="work-index"><span>{String(index+1).padStart(2,"0")}</span><p>{project.area}</p></div><div className="work-main"><div><h3>{project.title}</h3><span>{project.tech}</span></div><p>{project.summary}</p><ul>{project.details.map(detail=><li key={detail}>{detail}</li>)}</ul></div><span className="work-year">{project.year}</span></motion.article>)}</div></section>
  <section className="resume"><div className="section-label"><span>04</span><p>Background</p></div><div className="resume-content"><div className="resume-lead"><p>Currently shipping at</p><h2>PT Daging Grup Indonesia</h2><span>December 2024 — Present</span></div><div className="resume-rows"><article><span>Role</span><strong>Full-Stack Web Developer</strong><p>Web products, operational systems, integrations, and AI workflows.</p></article><article><span>Education</span><strong>Universitas Pamulang</strong><p>Informatics Engineering · Awaiting graduation.</p></article><article><span>Code</span><strong>GitLab · @hendyayanoyy</strong><p>Selected repositories and development activity.</p></article></div></div></section>
  <footer className="contact" id="contact"><div className="contact-top"><div className="section-label"><span>05</span><p>Start a conversation</p></div><p>Available for a full-time role and selected collaborations.</p></div><div className="contact-main"><p>Have a useful problem?</p><h2>Let&apos;s make it work.</h2></div><div className="contact-links"><a href="mailto:hendisaputra2205@gmail.com"><span>Email</span><strong>hendisaputra2205@gmail.com</strong><Arrow/></a><a href="https://wa.me/6289651147717" target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>+62 896-5114-7717</strong><Arrow/></a><a href="https://gitlab.com/hendyayanoyy" target="_blank" rel="noreferrer"><span>GitLab</span><strong>@hendyayanoyy</strong><Arrow/></a></div><div className="contact-base"><span>Hendi Saputra © 2026</span><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
