"use client";
import { useEffect, useState } from "react";
import Lenis from "lenis";
import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring } from "motion/react";
import { projectCapture, projects } from "../projects";
const techLogos:Record<string,string>={"Next.js":"nextdotjs/ffffff","Nuxt 3":"nuxt/00DC82",React:"react/61DAFB",Vue:"vuedotjs/4FC08D",TypeScript:"typescript/3178C6","Node.js":"nodedotjs/5FA04E",NestJS:"nestjs/E0234E",Express:"express/ffffff",PostgreSQL:"postgresql/4169E1","Tailwind CSS":"tailwindcss/06B6D4","REST APIs":"fastapi/009688","AI Integrations":"openai/ffffff"};
const stackLanes=[
 {no:"01",title:"Frontend",items:["Next.js","Nuxt 3","React","Vue","TypeScript","Tailwind CSS"]},
 {no:"02",title:"Backend & Data",items:["Node.js","NestJS","Express","PostgreSQL","REST APIs"]},
 {no:"03",title:"AI & Integrations",items:["AI Integrations"]},
];
function Arrow(){return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 19 19 5M8 5h11v11"/></svg>}
function AiMark(){return <svg className="tech-ai-mark" aria-hidden="true" viewBox="0 0 24 24"><path d="M9.5 4A2.5 2.5 0 0 1 12 6.5v11a2.5 2.5 0 0 1-4.96.44A2.5 2.5 0 0 1 4.5 15.5a3 3 0 0 1 .34-5.98A2.5 2.5 0 0 1 9.5 4Z"/><path d="M14.5 4A2.5 2.5 0 0 0 12 6.5v11a2.5 2.5 0 0 0 4.96.44A2.5 2.5 0 0 0 19.5 15.5a3 3 0 0 0-.34-5.98A2.5 2.5 0 0 0 14.5 4Z"/><path d="M7.5 9.5H10M14 8h2.5v2.5M7.5 14H10M14 15.5h2.5"/><circle cx="7.5" cy="9.5" r=".65"/><circle cx="7.5" cy="14" r=".65"/><circle cx="16.5" cy="10.5" r=".65"/><circle cx="16.5" cy="15.5" r=".65"/></svg>}

export default function Portfolio(){
 const [openProject,setOpenProject]=useState<string|null>(null);
 const [activeTech,setActiveTech]=useState("Next.js");
 const reduced=useReducedMotion();const{scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:100,damping:25});
 useEffect(()=>{if(reduced)return;const lenis=new Lenis({duration:1.05,smoothWheel:true});let frame=0;const raf=(t:number)=>{lenis.raf(t);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(frame);lenis.destroy()}},[reduced]);
 const reveal=reduced?{initial:false as const}:{initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-10%"},transition:{duration:.7,ease:[.16,1,.3,1] as [number,number,number,number]}};
 return <main id="top" data-build="2026-08-25-selected-work-removed">
  <motion.div className="progress" style={{scaleX:progress}}/>
  <header className="site-head"><a className="wordmark" href="#top"><span>Hendi</span> Saputra</a><p>Full-stack developer<br/>Jakarta · Indonesia</p><nav aria-label="Primary navigation"><a href="#experience">Experience</a><a href="#about">About</a></nav><a className="head-cta" href="#contact">Let&apos;s talk <Arrow/></a></header>
  <section className="hero"><div className="hero-starfield" aria-hidden="true"><i className="stars"/><i className="stars2"/><i className="stars3"/></div><div className="hero-copy"><p className="eyebrow"><i/> Available for the right team</p><motion.h1 initial={reduced?false:{opacity:0,y:36}} animate={{opacity:1,y:0}} transition={{duration:.9,ease:[.16,1,.3,1]}}>Building digital products from interface to intelligence.</motion.h1><div className="hero-bottom"><p>I&apos;m Hendi, a full-stack web developer building web platforms, internal systems, integrations, and AI-assisted workflows.</p><a href="#experience">Explore experience <span>↓</span></a></div></div><motion.figure className="portrait" initial={reduced?false:{clipPath:"inset(100% 0 0 0)"}} animate={{clipPath:"inset(0% 0 0 0)"}} transition={{duration:1.1,delay:.15,ease:[.16,1,.3,1]}}><img src="/hendi-portrait.webp" alt="Hendi Saputra, Full-Stack Web Developer"/><figcaption><span>01 / Portrait</span><span>PT Daging Grup Indonesia · 2024—Now</span></figcaption></motion.figure></section>
  <section className="toolkit" aria-labelledby="toolkit-title"><div className="toolkit-head"><div><p id="toolkit-title">Core toolkit</p><span>Technologies I use to ship production work.</span></div><div className="toolkit-preview" aria-hidden="true">{activeTech==="AI Integrations"?<AiMark/>:<img src={`https://cdn.simpleicons.org/${techLogos[activeTech]}`} alt=""/>}<span>{activeTech}</span></div></div><div className="stack-lanes">{stackLanes.map(lane=><article className="stack-lane" key={lane.title}><header><span>{lane.no}</span><h2>{lane.title}</h2></header><div>{lane.items.map((item,index)=><button type="button" key={item} onMouseEnter={()=>setActiveTech(item)} onFocus={()=>setActiveTech(item)}><span>{item}</span>{index<lane.items.length-1&&<i>/</i>}</button>)}</div></article>)}</div></section>
  <section className="statement" id="about"><div className="section-label"><span>01</span><p>What I bring</p></div><motion.div className="statement-copy" {...reveal}><p>Not just pages. I work across the whole product loop—interface, API, data, infrastructure, integration, and iteration.</p><div className="service-list"><article><span>01</span><h3>Web platforms</h3><p>Fast public experiences and internal tools engineered around real business workflows.</p></article><article><span>02</span><h3>Full-stack systems</h3><p>Practical architecture from data models and APIs through deployment and observability.</p></article><article><span>03</span><h3>AI &amp; automation</h3><p>AI-assisted flows and integrations that reduce repetitive work instead of adding novelty.</p></article></div></motion.div></section>
  <section className="experience" id="experience"><div className="experience-head"><div className="section-label"><span>02</span><p>Experience</p></div><div><h2>Main products &amp; collaborations.</h2><p>A focused view of the platforms and brand experiences I have helped take from product requirements to production.</p></div></div><div className="experience-list">{projects.map((item,index)=>{const isOpen=openProject===item.slug;return <motion.article className={`experience-item${isOpen?" is-open":""}`} key={item.name} {...reveal}><button className="experience-row experience-trigger" type="button" onClick={()=>setOpenProject(isOpen?null:item.slug)} aria-expanded={isOpen} aria-controls={`project-${item.slug}`}><span className="experience-no">{String(index+1).padStart(2,"0")}</span><div className="experience-shot"><img src={projectCapture(item.visuals[0])} style={{objectPosition:item.visuals[0].position||"top"}} alt="" loading="lazy"/></div><div className="experience-title"><h3>{item.name}</h3><p>{item.role}</p></div><div className="experience-scope"><p>{item.scope}</p><span>{item.tech}</span></div><div className="experience-period"><span>{item.period}</span><i aria-hidden="true">{isOpen?"−":"+"}</i></div></button><AnimatePresence initial={false}>{isOpen&&<motion.div id={`project-${item.slug}`} className="project-panel" initial={reduced?false:{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.55,ease:[.16,1,.3,1]}}><div className="project-panel-inner"><div className="project-copy"><p>{item.intro}</p><ul>{item.contribution.map(point=><li key={point}>{point}</li>)}</ul><a href={item.url} target="_blank" rel="noreferrer">Visit live website <Arrow/></a></div><div className="project-visuals">{item.visuals.slice(0,2).map((visual,visualIndex)=><figure className="project-desktop" key={`${visual.label}-${visualIndex}`}><div><img src={projectCapture(visual)} style={{objectPosition:visual.position||"top"}} alt={`${item.name} — ${visual.label}`} loading="lazy"/></div><figcaption><span>Desktop {String(visualIndex+1).padStart(2,"0")}</span><p>{visual.label}</p></figcaption></figure>)}<figure className="project-mobile"><div><img src={item.mobileSrc??`https://image.thum.io/get/width/430/crop/900/noanimate/${item.url}`} alt={`${item.name} mobile website`} loading="lazy"/></div><figcaption><span>Mobile 01</span><p>Responsive view</p></figcaption></figure></div></div></motion.div>}</AnimatePresence></motion.article>})}</div></section>
  <section className="resume"><div className="section-label"><span>03</span><p>Background</p></div><div className="resume-content"><div className="resume-lead"><p>Currently shipping at</p><h2>PT Daging Grup Indonesia</h2><span>December 2024 — Present</span></div><div className="resume-rows"><article><span>Role</span><strong>Full-Stack Web Developer</strong><p>Web products, operational systems, integrations, and AI workflows.</p></article><article><span>Education</span><strong>Universitas Pamulang</strong><p>Informatics Engineering · Awaiting graduation.</p></article><article><span>Code</span><strong>GitLab · @hendyayanoyy</strong><p>Selected repositories and development activity.</p></article></div></div></section>
  <footer className="contact" id="contact"><div className="contact-top"><div className="section-label"><span>04</span><p>Start a conversation</p></div><p>Available for a full-time role and selected collaborations.</p></div><div className="contact-main"><p>Have a useful problem?</p><h2>Let&apos;s make it work.</h2></div><div className="contact-links"><a href="mailto:hendisaputra2205@gmail.com"><span>Email</span><strong>hendisaputra2205@gmail.com</strong><Arrow/></a><a href="https://wa.me/6289651147717" target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>+62 896-5114-7717</strong><Arrow/></a><a href="https://gitlab.com/hendyayanoyy" target="_blank" rel="noreferrer"><span>GitLab</span><strong>@hendyayanoyy</strong><Arrow/></a></div><div className="contact-base"><span>Hendi Saputra © 2026</span><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
